### ISSUE TITLE
Sample Rate Difference in esp-picotts Example

### ISSUE THREAD

**Issue by SleepInfinity** [DiUS/esp-picotts#8]
Hi! I’ve been experimenting with the esp-picotts component on an ESP32 S3 DevKit C with a MAX98357A I2S amplifier. One thing I noticed in the example code is that the I2S configuration in esp-box.c sets the sample rate to 22050 Hz, while the TTS engine itself generates 16000 Hz (16-bit mono) samples.

Code Reference: [esp-box.c#L60](https://github.com/DiUS/esp-picotts/blob/9fa1a76194e2b1903e39fbf4b66eeb99bcba552a/examples/boot_greeting/main/bsp/esp-box.c#L60)

Is there a reason why the example uses 22050 Hz here, even though the TTS samples are at 16000 Hz? I’m wondering if there’s an intended benefit of using 22050 Hz in this setup, or if there’s a specific context where 22050 Hz works best. Would love to know if you have any guidance on this!

Thanks a lot for your help!

**Comment by jmattsson** [comment]
There is no deep reason here beyond the `esp-box.c` being taken verbatim from the Espressif BSP 🙃. If the I2S supports 16000Hz, that would likely be a better value to use.

**Comment by SleepInfinity** [comment]
> There is no deep reason here beyond the `esp-box.c` being taken verbatim from the Espressif BSP 🙃. If the I2S supports 16000Hz, that would likely be a better value to use.

Yes its working now with 16000Hz
Thank you.

**Comment by jmattsson** [comment]
Ah excellent, thanks for letting me know!
